---
- name: Installing java in linux
  when: ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "RedHat"
  block:
    - name: Linux - add cassandra repo
      become: yes
      template:
        src: "cassandra.repo.j2"
        dest: "/etc/yum.repos.d/cassandra.repo"

    - name: Install Cassandra
      become: yes
      yum:
        name: cassandra
        state: present
        update_cache: yes
    
    - name: Start cassandra
      sysvinit:
        name: cassandra
        state: started
        enabled: yes

    # - name: Start cassandra
    #   shell: service cassandra start
      # systemd:
      #   name: cassandra
      #   state: started
      
    - name: Basic configuration
      include_tasks: linux-config.yml

# tasks file for cassandraInstall
- name: Installing elastic Serch in ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"
  block:
    - name: Add cassandra apt key
      apt_key:
        url: "https://www.apache.org/dist/cassandra/KEYS"
        state: present
        
    # Add the Cassandra apt repo. For versions 6 of the stack - use '40x-release':
    - name: Adding cassandra repo
      apt_repository:
        repo: deb http://www.apache.org/dist/cassandra/debian 40x main
        state: present

    #Install cassandra
    - name: Install cassandra with apt
      apt:
        name: cassandra
        update_cache: yes

    - name: Basic configuration
      include_tasks: ubuntu-config.yml