---
# tasks file for cassandraInstall
- name: Installing elastic Serch in ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"
  block:
    - name: Add cassandra apt key
      apt_key:
        url: "https://www.apache.org/dist/cassandra/KEYS"
        state: present
        
    # Add the Cassandra apt repo. For versions 6 of the stack - use '6.x-prerelease':
    - name: Adding cassandra repo
      apt_repository:
        repo: deb http://www.apache.org/dist/cassandra/debian 40x main
        state: present
    #Install cassandra
    - name: Install cassandra with apt
      apt:
        name: cassandra
        update_cache: yes

    #Add this line if endpoint is GossipingPropertyFileSnitch
    - name: Adding JVM_OPTS if endpoint is GossipingPropertyFileSnitch
      lineinfile:
        destfile: /etc/cassandra/cassandra-env.sh
        line: 'JVM_OPTS="$JVM_OPTS -Dcassandra.ignore_dc=true"'

    - name: Copy the template
      template:
        src: "cassandra.yaml.j2"
        dest: "/etc/cassandra/cassandra.yaml"

    - name: Default files to delete
      shell: ls
      args:
        chdir: /var/lib/cassandra/data/system/
      register: files_list
      
    - name: Deleting default data 
      register: detail
      file:
        state: absent
        path: /var/lib/cassandra/data/system/{{item}}
      with_items:
        - "{{files_list.stdout_lines}}"
      notify: Restarting Cassandra